language: node_js

cache:
  directories:
    - node_modules

node_js:
  - 8

env:
  - CMD=test
  - CMD=lint

after_script:
  - bash <(curl -s https://codecov.io/bash) > /dev/null

script: npm run $CMD
